import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  docs: [{ type: "autogenerated", dirName: "docs" }],
  api: [{ type: "autogenerated", dirName: "api" }],
};

export default sidebars;
